### ISSUE TITLE
Using `Install-Module` or `oneget` with this Provider

### ISSUE THREAD

**Issue by avdaredevil** [Arnavion/PsFtpProvider#4]
Hey man, awesome library! Is it possible to have this published (*if done already, instructions on the readme*) on [PowerShell online gallery](https://www.powershellgallery.com). So it can be installed like:

```powershell
Install-Module PsFtpProvider
```

**Comment by Arnavion** [comment]
I'll look into it.

Ref: https://docs.microsoft.com/en-us/powershell/gallery/psgallery/psgallery_faqs#how-can-i-publish-to-the-powershell-gallery

**Comment by Arnavion** [comment]
I don't want to commit to this. I'd have to start supporting it properly, in particular tracking FluentFTP releases for bugfixes / security fixes.

Better to leave it here on Github where the user has to make an effort to get it and can tweak it if they want.
