### ISSUE TITLE
Support for -Persist option

### ISSUE THREAD

**Issue by marcelvanderperk** [Arnavion/PsFtpProvider#5]
If I use the following command; 
`New-PSDrive -Name "D" -PSProvider "PsFtp" -Hostname "$host" -Port 21 -Root "/" -Credential $Credentials -Persist `
I get the following error; 
`New-PSDrive : When you use the Persist parameter, the root must be a file system location on a remote computer. `

I've tried to use other values for the root, but I cannot seem to get it to work. Is this option supported?

**Comment by Arnavion** [comment]
That option is specially designed to add mapped network drives outside of PowerShell, so [`New-PSDrive` only supports `-Persist` for the FileSystem provider.](https://github.com/PowerShell/PowerShell/blob/17b501c9faf152763fef6170741799750b229db7/src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs#L1406-L1407) Other providers cannot use it.

If you were just looking to add a drive automatically, add the `New-PSDrive` command to your `$PROFILE`.
